name: test_firestore_odm
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  cloud_firestore: ^4.7.0
  cloud_firestore_odm: ^1.0.0-dev.58
  firebase_core: ^2.12.0
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.0.0
  cloud_firestore_odm_generator: ^1.0.0-dev.58
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true
